---
title: "Untitled"
author: "Henry Nguyen"
date: "2024-10-30"
output: html_document
---



```{r}
library(ggplot2)
library(ggnewscale)
library(cowplot)
library(dplyr)
library(ggpubr)
library(summarytools)

d<-read.csv("C:/Users/henry/OneDrive/Documents/GitHub/atlas/dat/Atlas_Data.csv", header=T, row.names = 1, stringsAsFactors = T)
#freq(d$Tu)
d<-d[d$Diagnosis.class !="#N/A",]
d$Tumor <- d$Diagnosis.class
d$Tumor<-factor(d$Tumor)  #removed list of labels
#https://medialab.github.io/iwanthue/ #44 colors
colors<-c("#6a0033",
          "#e4016e",
          "#ff527b",
          "#360e15",
          "#ff757c",
          "#dc002d",
          "#ff9170",
          "#7a2000",
          "#ff7e40",
          "#ac5300",
          "#da6c00",
          "#401f00",
          "#ffb173",
          "#d79600",
          "#6a4800",
          "#d6c6b2",
          "#ddaf00",
          "#d6ca6f",
          "#6e6900",
          "#1d1c10",
          "#8db600",
          "#1b7a00",
          "#8ddb76",
          "#00b861",
          "#9ad5b1",
          "#005d3f",
          "#01bbb7",
          "#00444d",
          "#01afc7",
          "#54d8f9",
          "#0189dd",
          "#8ab5ff",
          "#5292ff",
          "#004690",
          "#00317f",
          "#4263ff",
          "#240a4e",
          "#271332",
          "#fa63ff",
          "#760078",
          "#ff77f6",
          "#8a005f",
          "#ffa5ca",
          "black","grey10","grey20","gray80","grey40","grey50","grey60","grey70","grey30") #can add one more "#ff4494"

lab<- d %>% group_by(Tumor) %>% summarize(x = mean(tsne1), y = mean(tsne2))

lab$Tumor<-as.character(lab$Tumor)

lab$Tumor<-factor(lab$Tumor, levels=unique(lab$Tumor))
lab$x<-as.numeric(lab$x)
lab$y<-as.numeric(lab$y)

p<-ggplot()+geom_point(data=d, aes(tsne1,tsne2,color=factor(Tumor)), size=0.75)+theme_pubr()+
  geom_text(data = lab, aes(x=x,y=y,label=Tumor), size=3)+
  annotate("text", x=-94, y=87, label= "t-SNE Dimensionality Reduction\n(5248 samples)", hjust = 0, fontface = "bold") + 
  annotate("text", x=-94, y=-75, size=3, label= "Angio. = Angiocentric\nBrMet = Breast Cancer Metastasis\nCerbllm = Cerebellum\nGCT = Germ Cell Tumor\nGN = Ganglioneuroma\nUM = Uveal Melanoma", hjust = 0) + 
  scale_color_manual(values=colors)+
  theme(legend.position = "none")+rremove("axis")+rremove("axis.text")+rremove("ticks")+rremove("xylab")+
  theme(panel.border = element_rect(colour = "black", fill=NA))

p1<-ggplot()+
  geom_point(data=d[d$Class2=="Choroid Plexus",],aes(tsne1,tsne2,color=Tumor),size=1)+
  scale_color_manual(values=colors[1], name="Choroid Plexus")+
  guides(color = guide_legend(override.aes=list(shape = 15, size=5), order = 1))+
  new_scale_color() +
  
  geom_point(data=d[d$Class2=="Diffuse Glioma",],aes(tsne1,tsne2,color=Tumor),size=1)+
  scale_color_manual(values=colors[2:6], name="Diffuse Glioma")+
  guides(color = guide_legend(override.aes=list(shape = 15, size=5, ncol=2), order = 2))+
  new_scale_color() +
  
  geom_point(data=d[d$Class2=="Discrete Glioma",],aes(tsne2,tsne2,color=Tumor),size=1)+
  scale_color_manual(values=colors[7:9], name="Discrete Glioma")+
  guides(color = guide_legend(override.aes=list(shape = 15, size=5), order = 3))+
  new_scale_color() +
  
  geom_point(data=d[d$Class2=="Embryonal",],aes(tsne1,tsne2,color=Tumor),size=1)+
  scale_color_manual(values=colors[10:21], name="Embryonal")+
  guides(color = guide_legend(override.aes=list(shape = 15, size=5), order = 4))+
  
  theme_classic()+theme(legend.title=element_text(face="bold"), legend.justification = "top")

p1l <- get_legend(p1)

p2<-ggplot()+
  geom_point(data=d[d$Class2=="Ependymal",],aes(tsne1,tsne2,color=Tumor),size=1)+
  scale_color_manual(values=colors[22:27], name="Ependymal")+
  guides(color = guide_legend(override.aes=list(shape = 15, size=5), order = 1))+
  new_scale_color() +
  
  geom_point(data=d[d$Class2=="Germ Cell",],aes(tsne1,tsne2,color=Tumor),size=1)+
  scale_color_manual(values=colors[28], name="Germ Cell")+
  guides(color = guide_legend(override.aes=list(shape = 15, size=5), order = 2))+
  new_scale_color() +
  
  geom_point(data=d[d$Class2=="Glioneuronal",],aes(tsne1,tsne2,color=Tumor),size=1)+
  scale_color_manual(values=colors[29:30], name="Glioneuronal")+
  guides(color = guide_legend(override.aes=list(shape = 15, size=5), order = 3))+
  new_scale_color() +
  
  geom_point(data=d[d$Class2=="Hematolymphoid",],aes(tsne1,tsne2,color=Tumor),size=1)+
  scale_color_manual(values=colors[31], name="Hematolymphoid")+
  guides(color = guide_legend(override.aes=list(shape = 15, size=5), order = 4))+
  new_scale_color() +
  
  geom_point(data=d[d$Class2=="Melanocytic",],aes(tsne1,tsne2,color=Tumor),size=1)+
  scale_color_manual(values=colors[32], name="Melanocytic")+
  guides(color = guide_legend(override.aes=list(shape = 15, size=5), order = 5))+
  new_scale_color() +
  
  geom_point(data=d[d$Class2=="Mesenchymal",],aes(tsne1,tsne2,color=Tumor),size=1)+
  scale_color_manual(values=colors[33:35], name="Mesenchymal")+
  guides(color = guide_legend(override.aes=list(shape = 15, size=5), order = 6))+
  
  theme_classic()+theme(legend.title=element_text(face="bold"),legend.justification = "top")

p2l <- get_legend(p2)

p3<-ggplot()+
  geom_point(data=d[d$Class2=="Nerve",],aes(tsne1,tsne2,color=Tumor),size=1)+
  scale_color_manual(values=colors[36:39], name="Nerve")+
  guides(color = guide_legend(override.aes=list(shape = 15, size=5), order = 1))+
  new_scale_color() +
  
  geom_point(data=d[d$Class2=="Sellar",],aes(tsne1,tsne2,color=Tumor),size=1)+
  scale_color_manual(values=colors[40:41], name="Sellar")+
  guides(color = guide_legend(override.aes=list(shape = 15, size=5), order = 2))+
  new_scale_color() +
  
  geom_point(data=d[d$Class2=="Metastasis",],aes(tsne1,tsne2,color=Tumor),size=1)+
  scale_color_manual(values=colors[42:46], name="Metastasis")+
  guides(color = guide_legend(override.aes=list(shape = 15, size=5), order = 3))+
  new_scale_color() +
  
  geom_point(data=d[d$Class2=="Non-tumor",],aes(tsne1,tsne2,color=Tumor),size=1)+
  scale_color_manual(values=c("black","grey10","grey20","gray80","grey40","grey50","grey60","grey70","grey30"), name="Non-tumor")+
  guides(color = guide_legend(override.aes=list(shape = 15, size=5), order = 4))+
  new_scale_color() +
  
  theme_classic()+theme(legend.title=element_text(face="bold"),legend.justification = "top")

p3l <- get_legend(p3)

plot_grid(p,p1l,p2l,p3l, ncol=4, rel_widths = c(6,1,1,1), align = 'hv')


```













```{r}
library(plotly)

# Main scatter plot (p)
p_plotly <- plot_ly(
  data = d,
  x = ~tsne1,
  y = ~tsne2,
  type = 'scatter',
  mode = 'markers',
  color = ~factor(Tumor),
  colors = c("#6a0033",
          "#e4016e",
          "#ff527b",
          "#360e15",
          "#ff757c",
          "#dc002d",
          "#ff9170",
          "#7a2000",
          "#ff7e40",
          "#ac5300",
          "#da6c00",
          "#401f00",
          "#ffb173",
          "#d79600",
          "#6a4800",
          "#d6c6b2",
          "#ddaf00",
          "#d6ca6f",
          "#6e6900",
          "#1d1c10",
          "#8db600",
          "#1b7a00",
          "#8ddb76",
          "#00b861",
          "#9ad5b1",
          "#005d3f",
          "#01bbb7",
          "#00444d",
          "#01afc7",
          "#54d8f9",
          "#0189dd",
          "#8ab5ff",
          "#5292ff",
          "#004690",
          "#00317f",
          "#4263ff",
          "#240a4e",
          "#271332",
          "#fa63ff",
          "#760078",
          "#ff77f6",
          "#8a005f",
          "#ffa5ca",
          "black","grey10","grey20","gray80","grey40","grey50","grey60","grey70","grey30"),
  marker = list(size = 2)
) %>%
  layout(
    annotations = list(
      list(
        x = -94, y = 87, 
        text = "t-SNE Dimensionality Reduction<br>(5248 samples)", 
        showarrow = FALSE, 
        font = list(size = 14, color = "black", family = "bold")
      ),
      list(
        x = -94, y = -75,
        text = "Angio. = Angiocentric<br>BrMet = Breast Cancer Metastasis<br>Cerbllm = Cerebellum<br>GCT = Germ Cell Tumor<br>GN = Ganglioneuroma<br>UM = Uveal Melanoma",
        showarrow = FALSE,
        font = list(size = 10, color = "black")
      )
    ),
    showlegend = FALSE,  # Hide legend if not needed
    xaxis = list(visible = FALSE),
    yaxis = list(visible = FALSE),
    paper_bgcolor = "white"
  )



interactive_grid <- subplot(
  p_plotly,
  nrows = 1,
  widths = c(0.6),
  margin = 0.05
) %>%
  layout(showlegend = FALSE)

# Display the interactive grid
interactive_grid
```







