
# System

```{r options}

source('R/sysOpsLibsFuncs.R')


```

# ETL

## Load

```{r data}

# ubuntu
# geneExpressionData <- readRDS('/mnt/KDPH/PQI/Division Office/PQI Data Analytics/BrainTumorAtlas-main/Gene Expression Data/ExpData.rds')
# atlasData <- read_csv('/mnt/KDPH/PQI/Division Office/PQI Data Analytics/BrainTumorAtlas-main/Atlas_Data.csv')

# windows

# geneExpressionData <- readRDS("P:/PQI/Division Office/PQI Data Analytics/BrainTumorAtlas-main/Gene Expression Data/ExpData.rds")
# # atlasData <- read_csv('dat/Atlas_Data.csv')
# save(atlasData, file = 'dat/atlasData.RData')

load("dat/atlasData.RData")
load("dat/geneExpressionData.RData")

# Diverge from original data set
# atlasDataClean <- atlasData
load("dat/atlasDataClean.RData")

# annotations
load('dat/annotations.RData')
```




## Rename

```{r}

message('Rename begin..')

oldNames <- names(atlasData)

cleanNames <- c(
  'filename',
  'dataID',
  'sampleID',
  'institution',
  'country',
  'histologyOriginal',
  'subgroup',
  'locationOriginal',
  'compartment',
  'location',
  'stageNeuroblastoma',
  'stageMedulloblastoma',
  'tissuePrep',
  'sampleAnalysisGroup',
  'diagnosis',
  'grade',
  'fullName',
  'diagnosisClass',
  'classifierLightGBM',
  'classifierRandomForest',
  'classifierEuclidean',
  'classifierTSNE',
  'diagnosisFinal',
  'tsne1',
  'tsne2',
  'age',
  'ageGroup',
  'sex',
  'tumorType',
  'mortality',
  'survivalMonths',
  '1p/19q-codel',
  'mutationIDH1/2',
  'mutationH3',
  'mutationTERTpromoter',
  'amplificationEGFR',
  'methylationMGMTpromoter',
  'mutationBRAF',
  'amplificationMCYN'
)
  
names(atlasDataClean) <- cleanNames


colNames <- tibble(row = 1:length(oldNames), oldNames, cleanNames)

message('Rename finished.')
```

## Transform

```{r}

message("Transform begin..")

atlasDataClean <- atlasDataClean %>%
  mutate(
    across( 
     .cols = where(is.character),
     str_to_upper # ALL CAPS for only char data
    )
)



message("Transform finished.")

```

## Recode

```{r}

message("Recode begin..")

# Define the vector for both ageGroup levels and labels
# age_groups <- c("FETAL", "0-5YRS", "5-10YRS", "10-20YRS", "20-40YRS", "40-60YRS", "60-80YRS", "80+YRS")


atlasDataClean <- atlasDataClean %>%
  mutate(
    tumorType = ifelse(tumorType %in% c('PRIMARY', 'RECURRENT'), tumorType, NA), # flip n=19 to NA because inexclusive
    grade = ifelse(grade %in% paste0('GRADE ', 1:4), grade, NA), # flip n=11 to NA because inexclusive
    survivalMonths = as.double(survivalMonths),
    ageGroup = factor(ageGroup, levels = c("FETAL", "0-5YRS", "5-10YRS", "10-20YRS", "20-40YRS", "40-60YRS", "60-80YRS", "80+YRS")),
    across(
      c(grade, tumorType, sex, compartment, fullName, country),
      as.factor
    )
)


# freq(atlasDataClean$survivalMonths) %>% filter(str_detect(var, '[^0-9.]')) # n=104 # not a digit, not a period
# freq(atlasDataClean$age) %>% filter(str_detect(var, "[^0-9.]")) # n=590 # not a digit, not a period


message("Recode finished.")

```


## Filter

```{r}

message("Filter begin..")

atlasDataClean <- atlasDataClean %>% 
  filter(sampleAnalysisGroup %notin% 'TEST - NOT CLASSIFIED') # n=79 samples unable to assign a confident final diagnosis


# verifies record deletion
# select(atlasDataClean, sampleAnalysisGroup, diagnosisFinal) %>% filter(sampleAnalysisGroup == 'TEST - NOT CLASSIFIED') %>% view

message("Filter finished.")


```


## Select

```{r}


message("Select begin..")



atlasDataClean <- atlasDataClean %>% 
  select(everything())

message("Select finished.")

```


# Save

```{r}


save(atlasDataClean, file = 'dat/atlasDataClean.RData')

```



