
# Primary annotation assignment

```{r}
message("Annotation pipeline begin..")

library(org.Hs.eg.db)

# Column Availability
# cols_available <- columns(org.Hs.eg.db)

# Map Entrez IDs to Gene Symbols and Names
gene_annotations <- AnnotationDbi::select(org.Hs.eg.db,
  keys = rownames(geneExpressionData),
  columns = c("SYMBOL", "GENENAME"),
  # columns = cols_available,
  keytype = "ENTREZID"
)

# Potential shift in data structure
# geneExpressionDataAnnotated <- merge(geneExpressionData, gene_annotations, by.x = "row.names", by.y = "ENTREZID", all.x = TRUE)
library(dplyr)

# Assuming geneExpressionData is a data frame with gene IDs as row names
geneExpressionDataAnnotated <- geneExpressionData %>%
  rownames_to_column(var = "ENTREZID") %>% # Convert row names to a column
  inner_join(gene_annotations, by = "ENTREZID") %>%
  dplyr::select(ENTREZID, SYMBOL, GENENAME, everything())
```


# Find missing annotations

```{r}
message("Find missing annotations begin..")

library(rentrez)

fetch_gene_info <- function(id) {
  result <- entrez_summary(db = "gene", id = id)
  return(data.frame(
    ENTREZID = id,
    SYMBOL = result$name,
    GENENAME = result$description
  ))
}

# Fetch info for missing IDs
missing_ids <- gene_annotations$ENTREZID[is.na(gene_annotations$SYMBOL)]
new_annotations <- do.call(rbind, lapply(missing_ids, fetch_gene_info))

message("Find missing finished.")
```

## Add annotations where SYMBOL is NA


```{r}
message(paste0("Adding ", nrow(new_annotations), " missing annotation(s).."))

# glimpse(gene_annotations)
# table(is.na(gene_annotations$SYMBOL))
# glimpse(new_annotations)
library(dplyr)

# Update gene_annotations where SYMBOL is NA using new_annotations
gene_annotations <- gene_annotations %>%
  left_join(new_annotations, by = "ENTREZID", suffix = c(".orig", ".new")) %>%
  mutate(
    SYMBOL = if_else(is.na(SYMBOL.orig), SYMBOL.new, SYMBOL.orig),
    GENENAME = if_else(is.na(SYMBOL.orig), GENENAME.new, GENENAME.orig)
  ) %>%
  dplyr::select(ENTREZID, SYMBOL, GENENAME)

# Check the number of NAs in SYMBOL after updating
# table(is.na(gene_annotations$SYMBOL))
# freq(is.na(gene_annotations$SYMBOL))
# li(gene_annotations$ENTREZID, rownames(geneExpressionData))

message(paste0("Added ", nrow(new_annotations), " missing annotation(s)."))
```



# Gene Ontology
## Biological process 1

```{r}
message("Biological process begin..")

library(clusterProfiler)

# gene ontology terms
go_annotations <- enrichGO(
  gene = rownames(geneExpressionData),
  OrgDb = org.Hs.eg.db,
  ont = "BP", # Biological Process (or: “BP”, “MF”, “CC”, “ALL”)
  keyType = "ENTREZID"
)
# head(go_annotations)

# Extract gene-to-GO mapping
# This creates a named list where:
#
# The names are GO terms (descriptions).
# The values are comma-separated gene IDs.
go_to_genes <- setNames(go_annotations@result$geneID, go_annotations@result$Description)

# Split the gene IDs into vectors
go_to_genes_list <- lapply(go_to_genes, function(x) unlist(strsplit(x, "/")))

# Find overlap with your gene expression data
# mapped_genes <- lapply(go_to_genes_list, function(genes) {
#   intersect(genes, rownames(geneExpressionData))
# })

message("Biological process finished.")
```



```{r}
# all_possible_genes <- select(gene_annotations, SYMBOL) %>%
#   filter(!is.na(SYMBOL)) %>%
#   pull(SYMBOL)

all_valid_genes <- gene_annotations %>%
  filter(ENTREZID %in% rownames(geneExpressionData)) %>%
  pull(SYMBOL) %>%
  unique() %>%
  sort()
```

# Save

```{r}
save(gene_annotations, go_to_genes_list, all_valid_genes, file = "dat/annotations.RData")

message("Annotation pipeline finished.")
```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```

